stages:
  - "Build and Test"
  - "Deploy API"
  - "Deploy Web"

jobs:
  include:
  - language: csharp
    stage: "Build and Test"
    mono: none
    dotnet: 2.1
    before_script:
    - cd api
    - dotnet restore
    script:
    - dotnet build --no-restore --no-incremental
    - dotnet test QCVOC.Api.Tests.Unit/QCVOC.Api.Tests.Unit.csproj
  - language: csharp
    stage: "Deploy API"
    mono: none
    dotnet: 2.1
    before_script:
    - cd api
    script: skip
    before_deploy:
    - dotnet publish --configuration Release
    - cd QCVOC.Api/bin/Release/netcoreapp2.1/publish
    deploy:
      - provider: lambda
        access_key_id: AKIAQ6CU6LZRQ5IJHL5N
        secret_access_key:
          secure: fBEtYqaGUU6tsG58XoWzczn39WbNMANIcKhhYL1sAsyfGORFZ3oX36b2v62I1aCW2XDQ6uPTxkyAN7KxcUlPscyp7bULOjmMQ8A8YozTRjzacf1+3oII9dyWudfE4ETjPTcg4gyj+bkgJmOjwBxaTNvh37WfB+FM9jcvLhkBSbMszd/wHQdy1g9592GO4lj2OAkBfFBvNSl+8xH/AAh/U28Kc6HUaQfdpDL5dMY6ZLDZ46E6dADIJbJE4fgb1wu0oJdU7x2fana/ts6aYakvDS4Wika6NOaa1X8AjY6QAejRM+pQ/IAJ4cOD8WV/EGQ6Ev8lN8ucwtT2UmATGLGn30fKciOhSmfBFB/Z3JklVTiQARaMzwHOA4R5CGj7K5mF4FDnxJtg7Q81CFzC3WJe2IAw2sd3XuLFAzXoC5EsqTIkadgnYV1weMDlt5XwMs6sJ/CBjA1AIvT5EceoJEAWiDgS9FYyOM4Xl8/pGtb61Qeaw4CzeJpkKG5J6PrxKb5BH7i1mVwOnt3jEK8v5p447sjIhARpiujb1pLQBLxlTBSQPzAr8mvxS1wnRMFyIz6MXOWMKJ9QwyUtT/K1WTjCLFNCrtY1GE5wSs7+pSjklcT+w1JL1CXO96QHV9cxuSUpK53xAmjc5hZuIGstNEjWSB4lnOp8JThTV9Fk+N+SpoE=
        region: us-east-2
        function_name: qcvoc-dev
        role: arn:aws:iam::064602660451:role/qcvoc-lambda
        runtime: dotnetcore2.1
        timeout: 30
        memory_size: 256
        module_name: QCVOC.Api::QCVOC.Api
        handler_name: LambdaEntryPoint::FunctionHandlerAsync
        on:
          repo: qccoders/QCVOC
          branch: develop
      - provider: lambda
        access_key_id: AKIAQ6CU6LZRQ5IJHL5N
        secret_access_key:
          secure: fBEtYqaGUU6tsG58XoWzczn39WbNMANIcKhhYL1sAsyfGORFZ3oX36b2v62I1aCW2XDQ6uPTxkyAN7KxcUlPscyp7bULOjmMQ8A8YozTRjzacf1+3oII9dyWudfE4ETjPTcg4gyj+bkgJmOjwBxaTNvh37WfB+FM9jcvLhkBSbMszd/wHQdy1g9592GO4lj2OAkBfFBvNSl+8xH/AAh/U28Kc6HUaQfdpDL5dMY6ZLDZ46E6dADIJbJE4fgb1wu0oJdU7x2fana/ts6aYakvDS4Wika6NOaa1X8AjY6QAejRM+pQ/IAJ4cOD8WV/EGQ6Ev8lN8ucwtT2UmATGLGn30fKciOhSmfBFB/Z3JklVTiQARaMzwHOA4R5CGj7K5mF4FDnxJtg7Q81CFzC3WJe2IAw2sd3XuLFAzXoC5EsqTIkadgnYV1weMDlt5XwMs6sJ/CBjA1AIvT5EceoJEAWiDgS9FYyOM4Xl8/pGtb61Qeaw4CzeJpkKG5J6PrxKb5BH7i1mVwOnt3jEK8v5p447sjIhARpiujb1pLQBLxlTBSQPzAr8mvxS1wnRMFyIz6MXOWMKJ9QwyUtT/K1WTjCLFNCrtY1GE5wSs7+pSjklcT+w1JL1CXO96QHV9cxuSUpK53xAmjc5hZuIGstNEjWSB4lnOp8JThTV9Fk+N+SpoE=
        region: us-east-2
        function_name: qcvoc-prod
        role: arn:aws:iam::064602660451:role/qcvoc-lambda
        runtime: dotnetcore2.1
        timeout: 30
        memory_size: 256
        module_name: QCVOC.Api::QCVOC.Api
        handler_name: LambdaEntryPoint::FunctionHandlerAsync
        on:
          repo: qccoders/QCVOC
          branch: master
  - language: node_js
    stage: "Build and Test"
    node_js:
    - stable
    before_script:
    - cd web
    - npm install
    cache:
      directories:
      - web/node_modules
    script:
    - npm test
    - npm run build
  - language: node_js
    stage: "Deploy Web"
    node_js:
    - stable
    before_script:
    - cd web
    - npm install
    cache:
      directories:
      - web/node_modules
    script:
    - npm run build
    deploy:
      - provider: s3
        access_key_id: AKIAQ6CU6LZRQ5IJHL5N
        secret_access_key:
          secure: fBEtYqaGUU6tsG58XoWzczn39WbNMANIcKhhYL1sAsyfGORFZ3oX36b2v62I1aCW2XDQ6uPTxkyAN7KxcUlPscyp7bULOjmMQ8A8YozTRjzacf1+3oII9dyWudfE4ETjPTcg4gyj+bkgJmOjwBxaTNvh37WfB+FM9jcvLhkBSbMszd/wHQdy1g9592GO4lj2OAkBfFBvNSl+8xH/AAh/U28Kc6HUaQfdpDL5dMY6ZLDZ46E6dADIJbJE4fgb1wu0oJdU7x2fana/ts6aYakvDS4Wika6NOaa1X8AjY6QAejRM+pQ/IAJ4cOD8WV/EGQ6Ev8lN8ucwtT2UmATGLGn30fKciOhSmfBFB/Z3JklVTiQARaMzwHOA4R5CGj7K5mF4FDnxJtg7Q81CFzC3WJe2IAw2sd3XuLFAzXoC5EsqTIkadgnYV1weMDlt5XwMs6sJ/CBjA1AIvT5EceoJEAWiDgS9FYyOM4Xl8/pGtb61Qeaw4CzeJpkKG5J6PrxKb5BH7i1mVwOnt3jEK8v5p447sjIhARpiujb1pLQBLxlTBSQPzAr8mvxS1wnRMFyIz6MXOWMKJ9QwyUtT/K1WTjCLFNCrtY1GE5wSs7+pSjklcT+w1JL1CXO96QHV9cxuSUpK53xAmjc5hZuIGstNEjWSB4lnOp8JThTV9Fk+N+SpoE=
        bucket: qcvoc-prod
        skip_cleanup: true
        local_dir: build
        region: us-east-2
        acl: public_read
        on:
          repo: qccoders/QCVOC
          branch: master
      - provider: s3
        access_key_id: AKIAQ6CU6LZRQ5IJHL5N
        secret_access_key:
          secure: fBEtYqaGUU6tsG58XoWzczn39WbNMANIcKhhYL1sAsyfGORFZ3oX36b2v62I1aCW2XDQ6uPTxkyAN7KxcUlPscyp7bULOjmMQ8A8YozTRjzacf1+3oII9dyWudfE4ETjPTcg4gyj+bkgJmOjwBxaTNvh37WfB+FM9jcvLhkBSbMszd/wHQdy1g9592GO4lj2OAkBfFBvNSl+8xH/AAh/U28Kc6HUaQfdpDL5dMY6ZLDZ46E6dADIJbJE4fgb1wu0oJdU7x2fana/ts6aYakvDS4Wika6NOaa1X8AjY6QAejRM+pQ/IAJ4cOD8WV/EGQ6Ev8lN8ucwtT2UmATGLGn30fKciOhSmfBFB/Z3JklVTiQARaMzwHOA4R5CGj7K5mF4FDnxJtg7Q81CFzC3WJe2IAw2sd3XuLFAzXoC5EsqTIkadgnYV1weMDlt5XwMs6sJ/CBjA1AIvT5EceoJEAWiDgS9FYyOM4Xl8/pGtb61Qeaw4CzeJpkKG5J6PrxKb5BH7i1mVwOnt3jEK8v5p447sjIhARpiujb1pLQBLxlTBSQPzAr8mvxS1wnRMFyIz6MXOWMKJ9QwyUtT/K1WTjCLFNCrtY1GE5wSs7+pSjklcT+w1JL1CXO96QHV9cxuSUpK53xAmjc5hZuIGstNEjWSB4lnOp8JThTV9Fk+N+SpoE=
        bucket: qcvoc-web-dev
        skip_cleanup: true
        local_dir: build
        region: us-east-2
        acl: public_read
        on:
          repo: qccoders/QCVOC
          branch: develop
  - language: android
    stage: "Build and Test"
    android:
      components:
        - build-tools-28.0.2
        - android-26
        - extra-google-google_play_services
    before_script:
    - cd mobile
    script:
    - ./gradlew --quiet build
