name: CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore
        working-directory: ./api
        run: dotnet restore
      - name: Build 
        working-directory: ./api
        run: dotnet build --no-restore --no-incremental
      - name: Test
        working-directory: ./api
        run: dotnet test QCVOC.Api.Tests.Unit/QCVOC.Api.Tests.Unit.csproj