name: CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  api:
    name: Build and Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cd api
          dotnet restore
          dotnet build --no-restore --no-incremental
          dotnet test QCVOC.Api.Tests.Unit/QCVOC.Api.Tests.Unit.csproj
      - name: Publish
        run: |
          cd api
          dotnet publish --configuration Release
      - name: Zip API
        run: |
          cd api
          cd QCVOC.Api/bin/Release/netcoreapp3.1/publish
          zip -r ../../../../../../api.zip .
      - name: Upload API Zip
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip
  web:
    name: Build and Test Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        working-directory: ./web
        run: npm install
      - name: Test and Build
        working-directory: ./web
        run: npm test && npm run build
      - name: Upload Static Web Content
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: web/build
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [api, web]
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Download Static Web Content
        uses: actions/download-artifact@v2
        with:
          name: web
          path: web
      - name: Download API Zip
        uses: actions/download-artifact@v2
        with:
          name: api
          path: .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

